---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("tximport")
```

```{r}
library(GenomicFeatures)
library(AnnotationDbi)
```

```{r}
#BiocManager::install("txdbmaker")
library (txdbmaker)
```

```{r}
if ("BiocIO" %in% rownames(installed.packages())) {
  remove.packages("BiocIO")
}

BiocManager::install("BiocIO")
library (BiocIO)
```

```{r}
if (!requireNamespace("rtracklayer", quietly = TRUE))
    BiocManager::install("rtracklayer")
library(rtracklayer)

```

```{r}
gtf_file <- "../../data/covid_dataset/gencode.v46.annotation.gtf"
```

```{r}
txdb <- GenomicFeatures::makeTxDbFromGFF(gtf_file, format = "gtf")
tx2gene <- ensembldb::select(txdb, keys = keys(txdb, "TXNAME"),
                  columns = c("TXNAME", "GENEID"),
                  keytype = "TXNAME")
colnames(tx2gene) <- c("tx_id", "gene_id")

```

```{r}
str(tx2gene)
```

```{r}
dir <- "../../data/covid_dataset/"
files <- list.files(path = dir, pattern = "abundance.tsv.gz$", full.names = TRUE)
# SRR11614663_GSM4499449_1_1.abundance.tsv.gz
# SRR11614664_GSM4499451_1_2.abundance.tsv.gz
# SRR11614665_GSM4499454_1b24_1.abundance.tsv.gz
# SRR11614666_GSM4499456_1b24_2.abundance.tsv.gz
# SRR11614667_GSM4499458_1b60_1.abundance.tsv.gz
# SRR11614668_GSM4499460_1b60_2.abundance.tsv.gz
# SRR11614671_GSM4499468_6a24_1.abundance.tsv.gz
# SRR11614672_GSM4499470_6a24_2.abundance.tsv.gz
# SRR11614673_GSM4499472_6a60_1.abundance.tsv.gz
# SRR11614674_GSM4499475_6a60_2.abundance.tsv.gz
sample_names <- basename(files)
print(sample_names)
print(files)
```

```{r}
library (tidyr)
sampleTable <- data.frame(
  sampleID = sample_names,
  infection = factor (c("Uninfected", "Uninfected", 
                        "SARS-CoV", "SARS-CoV", 
                        "SARS-CoV", "SARS-CoV", 
                        "SARS-CoV-2", "SARS-CoV-2", "SARS-CoV-2", "SARS-CoV-2")),  
  time = factor(c("0h", "0h", "24h", "24h", "60h", 
                  "60h", "24h", "24h", "60h", "60h"))
)
#sampleTable <- sampleTable %>% unite(infection_time, c("infection", "time"))
#unique (sampleTable$infection_time)

sampleTable$infection <- as.factor(sampleTable$infection)
sampleTable$time <- as.factor(sampleTable$time)

```

```{r}
library (tximport)
txi.kallisto <- tximport(files, type = "kallisto", tx2gene = tx2gene, ignoreAfterBar = TRUE)
#View (txi.kallisto$counts)
```
```{r}
if (!requireNamespace("org.Hs.eg.db", quietly = TRUE)) {
    BiocManager::install("org.Hs.eg.db")
}
library(org.Hs.eg.db)
```

```{r}
ens_ids <- rownames(txi.kallisto$counts)
View(ens_ids)
```

```{r}
library(stringr)
ens_ids_clean <- str_remove(ens_ids, "\\..*$")

```

```{r}
gene_names <- mapIds(org.Hs.eg.db, keys = ens_ids_clean, column = "SYMBOL", keytype = "ENSEMBL", multiVals = "first")
gene_names_all <- ifelse(is.na(gene_names), ens_ids_clean, gene_names)

rownames(txi.kallisto$counts) <- gene_names_all
View (txi.kallisto$counts)
```
```{r}
any_na <- any(is.na(txi.kallisto$counts))
print (any_na)

```

```{r}
library(DESeq2)

```

```{r}
dds_SARS <- DESeqDataSetFromTximport (txi.kallisto, 
                                      colData=sampleTable, 
                                      design= ~ infection + time + infection:time)

dds_SARS <- DESeq(dds_SARS)

```

```{r}
colData(dds_SARS)
```


```{r}
library (dplyr)

res_SARS1_vs_SARS2_24h <- results(dds_SARS, contrast= c("infection_time", "SARS-CoV_24h", "SARS-CoV-2_24h"))
res_SARS1_vs_SARS2_24h <- res_SARS1_vs_SARS2_24h %>% as.data.frame() %>% filter(abs(log2FoldChange) > 1, padj < 0.05) %>% arrange(desc(log2FoldChange))
head (res_SARS1_vs_SARS2_24h)

res_SARS1_vs_SARS2_60h <- results(dds_SARS, contrast= c("infection_time", "SARS-CoV_60h", "SARS-CoV-2_60h"))
res_SARS1_vs_SARS2_60h <- res_SARS1_vs_SARS2_60h %>% as.data.frame() %>% filter(abs(log2FoldChange) > 1.5, padj < 0.05) %>% arrange(desc(log2FoldChange))
head (res_SARS1_vs_SARS2_60h)

res_uninf_vs_SARS2_24h <- results(dds_SARS, contrast= c("infection_time", "Uninfected_0h", "SARS-CoV-2_24h"))
res_uninf_vs_SARS2_24h <- res_uninf_vs_SARS2_24h %>% as.data.frame() %>% filter(abs(log2FoldChange) > 1.5, padj < 0.05) %>% arrange(desc(log2FoldChange))
head (res_uninf_vs_SARS2_24h)

res_uninf_vs_SARS2_60h <- results(dds_SARS, contrast= c("infection_time", "Uninfected_0h", "SARS-CoV-2_60h"))
res_uninf_vs_SARS2_60h <- res_uninf_vs_SARS2_60h %>% as.data.frame() %>% filter(abs(log2FoldChange) > 1.5, padj < 0.05) %>% arrange(desc(log2FoldChange))
head (res_uninf_vs_SARS2_60h)

res_uninf_vs_SARS1_24h <- results(dds_SARS, contrast= c("infection_time", "Uninfected_0h", "SARS-CoV_24h"))
res_uninf_vs_SARS1_24h <- res_uninf_vs_SARS1_24h %>% as.data.frame() %>% filter(abs(log2FoldChange) > 1.5, padj < 0.05) %>% arrange(desc(log2FoldChange))
head (res_uninf_vs_SARS1_24h)

res_uninf_vs_SARS1_60h <- results(dds_SARS, contrast= c("infection_time", "Uninfected_0h", "SARS-CoV_60h"))
res_uninf_vs_SARS1_60h <- res_uninf_vs_SARS1_60h %>% as.data.frame() %>% filter(abs(log2FoldChange) > 1.5, padj < 0.05) %>% arrange(desc(log2FoldChange))
head (res_uninf_vs_SARS1_60h)

```


```{r}
library(EnhancedVolcano)
volcano_df <- res_SARS1_vs_SARS2_60h %>% as.data.frame()
volcano_df

EnhancedVolcano(volcano_df,
                lab = rownames(volcano_df),
                x = "log2FoldChange",
                y = "padj", title="SARS-CoV vs SARS_CoV-2 at 60h")
```

```{r}
volcano_df_SARS1_vs_SARS2_24h <- res_SARS1_vs_SARS2_24h %>% as.data.frame()
volcano_df_SARS1_vs_SARS2_24h

EnhancedVolcano(volcano_df_SARS1_vs_SARS2_24h,
                lab = rownames(volcano_df_SARS1_vs_SARS2_24h),
                x = "log2FoldChange",
                y = "padj", title="SARS-CoV vs SARS_CoV-2 at 24h")
```
```{r}
volcano_df_uninf_vs_SARS2_24h <- res_uninf_vs_SARS2_24h %>% as.data.frame()
volcano_df_uninf_vs_SARS2_24h

EnhancedVolcano(volcano_df_uninf_vs_SARS2_24h,
                lab = rownames(volcano_df_uninf_vs_SARS2_24h),
                x = "log2FoldChange",
                y = "padj", title="Uninfected vs SARS_CoV-2 at 24h")
```

```{r}
volcano_df_uninf_vs_SARS2_60h <- res_uninf_vs_SARS2_60h %>% as.data.frame()
volcano_df_uninf_vs_SARS2_60h

EnhancedVolcano(volcano_df_uninf_vs_SARS2_60h,
                lab = rownames(volcano_df_uninf_vs_SARS2_60h),
                x = "log2FoldChange",
                y = "padj", title="Uninfected vs SARS_CoV-2 at 60h")
```

```{r}
volcano_df_uninf_vs_SARS1_24h <- res_uninf_vs_SARS1_24h %>% as.data.frame()
volcano_df_uninf_vs_SARS1_24h

EnhancedVolcano(volcano_df_uninf_vs_SARS1_24h,
                lab = rownames(volcano_df_uninf_vs_SARS1_24h),
                x = "log2FoldChange",
                y = "padj", title="Uninfected vs SARS_CoV-1 at 24h")
```

```{r}
volcano_df_uninf_vs_SARS1_60h <- res_uninf_vs_SARS1_60h %>% as.data.frame()
volcano_df_uninf_vs_SARS1_60h

EnhancedVolcano(volcano_df_uninf_vs_SARS1_60h,
                lab = rownames(volcano_df_uninf_vs_SARS1_60h),
                x = "log2FoldChange",
                y = "padj", title="Uninfected vs SARS_CoV-1 at 60h")
```

